services:
  - type: web
    name: nutrition-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: nutrition-app-db
          property: connectionString

databases:
  - name: nutrition-app-db
    databaseName: nutrition_app
    user: nutrition_user
    plan: free
